### ISSUE TITLE
NameError: name 'LR_filename' is not defined

### ISSUE THREAD

**Issue by thoppe** [Holmes-Alan/dSRVAE#1]
Running `test.py` gives the following error:

```
Namespace(chop_forward=True, gpu_mode=True, gpus=1, input='Test', model_SR='models/VAE_SR.pth', model_denoiser='models/VAE_denoiser.pth', model_type='VAE', output='Result', patch_size=128, seed=123, stride=8, testBatchSize=64, threads=6, upscale_factor=4)
===> Building model  VAE
===> Loading datasets
Pre-trained Denoiser model is loaded.
Pre-trained SR model is loaded.
Traceback (most recent call last):
  File "test.py", line 151, in <module>
    eval()
  File "test.py", line 86, in eval
    SR_image = [join(opt.Result, x) for x in listdir(LR_filename) if is_image_file(x)]
NameError: name 'LR_filename' is not defined
```

Not sure what `LR_filename` is since it's not defined anywhere else in the code. How can I get your test to run?

**Comment by Holmes-Alan** [comment]
Thanks for letting me know. Problem has been fixed.
