### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by mgrankin** [Holmes-Alan/dSRVAE#4]
During launch of `python main_denoiser.py`

```
Traceback (most recent call last):
  File "main_denoiser.py", line 142, in <module>
    train(epoch)
  File "main_denoiser.py", line 52, in train
    for iteration, batch in enumerate(training_data_loader, 1):
  File "/home/u/.anaconda/envs/fast_tabnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/u/.anaconda/envs/fast_tabnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/u/.anaconda/envs/fast_tabnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/u/.anaconda/envs/fast_tabnet/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/u/.anaconda/envs/fast_tabnet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/u/.anaconda/envs/fast_tabnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/u/.anaconda/envs/fast_tabnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/u/dSRVAE/datasets.py", line 105, in __getitem__
    ref = load_img(self.hr_image_filenames[2649-index])
IndexError: list index out of range
```

**Comment by Holmes-Alan** [comment]
it reads images from the folder and you can check the filepath and make your own modification.

**Comment by mgrankin** [comment]
It would be useful to have information about directory structure in the readme for the purpose of replication. Like which NTIRE2020 zip goes to which directory.
